### ISSUE TITLE
ValueError: 'group' is not a valid MonitorType

### ISSUE THREAD

**Issue by justinkruit** [Peppershade/uptimekuma-migrator#4]
Tried to do a migration, but I'm running into the following error:
```
PS E:\Documents\Projects\Work\Uptime\uptimekuma-migrator-main> python .\migrator.py
Fetching monitors from UptimeRobot API.
Fetched 50 monitors from UptimeRobot API.
Fetching monitors from UptimeRobot API with offset 50.
Fetched 98 monitors from UptimeRobot API.
Syncing monitors to Uptime Kuma API.
Traceback (most recent call last):
  File "E:\Documents\Projects\Work\Uptime\uptimekuma-migrator-main\migrator.py", line 192, in <module>
    sync_monitor_to_uptimekuma(monitor)
  File "E:\Documents\Projects\Work\Uptime\uptimekuma-migrator-main\migrator.py", line 66, in sync_monitor_to_uptimekuma
    if check_if_monitor_exists(monitor):
  File "E:\Documents\Projects\Work\Uptime\uptimekuma-migrator-main\migrator.py", line 156, in check_if_monitor_exists
    monitors = api.get_monitors()
  File "C:\Users\justinkruit\AppData\Local\Programs\Python\Python310\lib\site-packages\uptime_kuma_api\api.py", line 1023, in get_monitors
    parse_monitor_type(r)
  File "C:\Users\justinkruit\AppData\Local\Programs\Python\Python310\lib\site-packages\uptime_kuma_api\api.py", line 72, in parse_monitor_type
    parse_value(data, "type", MonitorType)
  File "C:\Users\justinkruit\AppData\Local\Programs\Python\Python310\lib\site-packages\uptime_kuma_api\api.py", line 57, in parse_value
    parse_value(d, key, type_, default)
  File "C:\Users\justinkruit\AppData\Local\Programs\Python\Python310\lib\site-packages\uptime_kuma_api\api.py", line 61, in parse_value
    data[key] = type_(data[key])
  File "C:\Users\justinkruit\AppData\Local\Programs\Python\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\justinkruit\AppData\Local\Programs\Python\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'group' is not a valid MonitorType
```

**Comment by justinkruit** [comment]
Seems like this is a uptime-kuma-api issue and has already been reported: https://github.com/lucasheld/uptime-kuma-api/issues/40
